import mongoose from 'mongoose'

const OrderItemSchema = new mongoose.Schema({
  name: String, qty: Number, unit: String, price: Number,
})

const OrderSchema = new mongoose.Schema({
  orderId:        { type: String, unique: true, required: true },
  customerId:     { type: mongoose.Schema.Types.ObjectId, ref: 'Customer', required: true },
  customerName:   String,
  customerPhone:  String,
  customerEmail:  String,
  farmerId:       String,
  farmerName:     String,
  farmerPhone:    String,
  farmerEmail:    String,
  farmerAddress:  String,
  farmerLocation: { lat: Number, lng: Number },
  deliveryPartnerId: { type: mongoose.Schema.Types.ObjectId, ref: 'DeliveryPartner', default: null },
  deliveryPartnerName: String,
  deliveryPhone: String,
  deliveryEmail: String,
  items:          [OrderItemSchema],
  status:         { type: String, default: 'placed', enum: ['placed','confirmed','picked_up','on_the_way','delivered','cancelled'] },
  subtotal:       Number,
  pack:           { type: String, enum: ['small', 'medium', 'large'], default: 'small' },
  platformFee:    { type: Number, default: 0 },
  platformCommission: { type: Number, default: 0 },
  deliveryFee:    { type: Number, default: 0 },
  deliveryAgentFee: { type: Number, default: 0 },
  farmerSettlementStatus: { type: String, enum: ['pending', 'settled'], default: 'pending' },
  deliverySettlementStatus: { type: String, enum: ['pending', 'settled'], default: 'pending' },
  farmerSettledAt: Date,
  deliverySettledAt: Date,
  distanceKm:     Number,
  total:          Number,
  address:        String,
  deliveryAddress: {
    recipientName: String,
    flatHouse: String,
    street: String,
    landmark: String,
    area: String,
    city: String,
    pincode: String,
  },
  location:       { lat: Number, lng: Number },
  deliveryNote:   String,
  paymentMethod:  { type: String, enum: ['online', 'cod'], default: 'online' },
  depositAmount:  { type: Number, default: 0 },
  paymentId:      { type: String, default: null },
  paymentStatus:  { type: String, default: 'pending', enum: ['pending','deposit_paid','paid','failed','refunded'] },
  razorpayOrderId:{ type: String, default: null },
  liveLocation:   {
    lat: { type: Number, default: null },
    lng: { type: Number, default: null },
    updatedAt: { type: Date, default: null },
  },
  feedbackRating: { type: Number, min: 1, max: 5, default: null },
  feedbackComment: { type: String, default: '' },
  feedbackAt: { type: Date, default: null },
}, { timestamps: true })

export default mongoose.models.Order || mongoose.model('Order', OrderSchema)
